### ISSUE TITLE
Supported version (checksum error)

### ISSUE THREAD

**Issue by BASM** [dfint/df-steam-hook-rs#29]
Hello. I build df-steam-hook-rs on the Ubuntu 22.04 LTS.

Wget and unpack df_50_11_linux.tar.bz2, copy df-steam-hook-rs/target/release/libdfint_hook.so to  df_50_11_linux/libdfhooks.so and run ./dwarfort

I have got error:

```
Broken unicode: [KEY:ÿ]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/config.rs:93:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
terminate called without an active exception
zsh: IOT instruction (core dumped)  ./dwarfort
```

strace says me what files not found:
* dfint-data/config.toml
* dfint-data/dictionary.csv
* dfint_data/dfint_log.log

I copy files from win hook.

dfint_data/dfint_log.log says:
```
[00:00:00.000] (7ffb4d496100) INFO   pe checksum: 0x193a321
[00:00:00.000] (7ffb4d496100) INFO   offsets version: not found
[00:00:00.000] (7ffb4d496100) INFO   hook version: not-defined
[00:00:00.000] (7ffb4d496100) INFO   dictionary "./dfint-data/dictionary.csv", items 30993
[00:00:03.207] (7ffb4d496100) DEBUG  hooks detached
```

What version is supported? Where I can got offset?

**Comment by BASM** [comment]
poetry run search ../../df5011/dwarfort

**Comment by insolor** [comment]
Hi

There is an [installer](https://github.com/dfint/installer/releases/tag/0.1.1), it gathers and installs all needed files. It hasn't yet announced because it is in an early development stage, not tested thoroughly, and has been configured only for Russian language just yet. I assume that you are using Russian, so you can participate in testing.

> poetry run search ../../df5011/dwarfort

The search script works only with Windows version of DF.

**Comment by BASM** [comment]
Thanks for answers. Can I create documentation in your Readme file if I am able to run it? Or would you prefer to do it yourself? I will continue working on it over the weekend.

**Comment by shevernitskiy** [comment]
Sure, it's open source. You could make a PR.

**Comment by BASM** [comment]
![a](https://github.com/dfint/df-steam-hook-rs/assets/157529/6dc01b8b-7d79-4a19-9ad8-e1bf76cbba91)

It seems to be working in some way. Am I correct in understanding that we cannot see on the fonts with 256 characters and normal frames? The translation also looks strange. Is this a work in progress, or did I do something wrong?

**Comment by shevernitskiy** [comment]
> It seems to be working in some way. Am I correct in understanding that we cannot see normal frames on the fonts with 256 characters? The translation also looks strange. Is this a work in progress, or did I do something wrong?

Yeah, it's working.
In ASCII mode frame borders are symbols. We use cp1251 instead of cp437, so there is flip side. Where the original char code seems to be border fragment, in cp1251 it is `Д ` (for example).
As for crappy translation - it is other flip side of this method of translation. We hooked some raw low level C function like `strncpy` and `strncat`. When this whole window beeing generated, those function called for just parts of whole sentences, and those part translated. After that half translated sentence simply doesn't match anything in dictionary. So we just trying to increase total amount of translated text in game in general.

**Comment by BASM** [comment]
Why not use CP866? It is the most well-adapted in terms of borders.

**Comment by insolor** [comment]
@BASM 

1. Historical reasons. In older DF versions, it was possible to use a separate ttf font which didn't clash with other graphics. So, actual encoding didn't matter that much at that time.
2. There are some special characters in cp437 which are used to show a quality of an item, for example `≡Exceptional quality item≡` or `«Decorated item»`. In cp1251 `≡` clashes with Russian р, but doesn't clash with `«»`. In cp866 `Ё` clashes with `≡` (but this is tolerable, we don't need capital Ё that much, we can just sacrifice it), but also `«»` symbols clash with `о` and `п`.
3. Also, capital case/lower case conversion for cp866 is a bit more complicated. Not that complicated, but anyway.

In general, it's historical reasons. May be in the future, when we implement external configuration of configuration for lower/upper case switching and similar stuff, we will switch.

**Comment by insolor** [comment]
@BASM we've added a font for cp866 https://github.com/dfint/update-data/tree/main/store/fonts

config for this encoding: https://github.com/dfint/update-data/tree/main/store/encodings

and a dictionary in this encoding: https://github.com/dfint/autobuild/tree/main/translation_build/csv_with_objects/Russian%20(cp866)

**Comment by BASM** [comment]
Now it looks really beautiful. Thanks!

It would be wonderful to find the right hook for long texts. Judging by the translation, the entire text is translated, but the same tutorial falls into the addst function, which passes the text one word at a time.

I tried to find it, but so far nothing has worked out, not enough experience. I continue to explore.

**Comment by shevernitskiy** [comment]
> Now it looks really beautiful. Thanks!
> 
> It would be wonderful to find the right hook for long texts. Judging by the translation, the entire text is translated, but the same tutorial falls into the addst function, which passes the text one word at a time.
> 
> I tried to find it, but so far nothing has worked out, not enough experience. I continue to explore.

There was an templete function for whole text. But we can't use it because there are no such strings in our dictionary. Dictionary keeps values from rdata (as I remember) section. And there is values by "word".

It can be translated in full manual mode in higher level function, i think. But it's not automated solution, hard to maintain.

**Comment by BASM** [comment]
Tutorial is using
_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm@@Base

On the win we can ignore this hook.

I will try to add this hook. Rust is a new language for me, so it will take some time.

**Comment by shevernitskiy** [comment]
I tried to hook `mutate` but have a crash everytime as a result.
Mutate is a internal gcc stl function as i understand. It is called by assing or append.
My guess is there is some data race and we don't have memory access when entering to our hooked `mutate` and searching in a dict map.
If you able to hook it and discover this crash under debugger, it could help to find the answer.

**Comment by shevernitskiy** [comment]
> Yes, I rushed. Usually, after calling the 'mutation' function, the append and assign functions are used. I used writenl!(stderr,) for print arguments 'src' (cxxstring) and 'dst' (char*), but some nonsense is being outputted. Maybe there are some issues with cxxstring, I'm investigating. I don't really understand how std string works yet, why it's char * up to 16 bytes and then some magic happens. I suspect that this magic is not working correctly.
> 
> What debuggers should I use to debug Rust? gdb?

cxxstring is my reimplementation of std::string for gcc and msvc stl... it migth be incorrect... 16 bytes is short string optimization technique... msvc and gcc use different ways for sso..

**Comment by insolor** [comment]
@BASM do you use telegram? Ping me https://t.me/insolor
