### ISSUE TITLE
Optimization of Readme Files

### ISSUE THREAD

**Issue by xxxxj-up** [dfint/df-steam-hook-rs#37]
May I ask What is target/release/libdfint_hook.so

I don't seem to see it in the release(Maybe it's because my native language is not English)

Since theoretically it can run normally on Windows

Can you provide a tutorial on how to run normally on Windows

**Comment by xxxxj-up** [comment]
ok...

I used the file provided in the release and compiled one myself. I followed the readme file and unfortunately, it didn't work

**Comment by insolor** [comment]
@xxxxj-up, in general, for windows everything is more or less the same, except you need `.dll` library instead of `.so`.

**Comment by xxxxj-up** [comment]
@insolor the hook_0.1.1.dll copy to libdfhooks.dll

**Comment by insolor** [comment]
> @insolor the hook_0.1.1.dll copy to libdfhooks.dll

Try without lib-

**Comment by xxxxj-up** [comment]
ok,it's work

**Comment by insolor** [comment]
@xxxxj-up well, you are right, but it was not expected that anyone would try to use it directly. It is intended to be installed and updated with an installer application (which is not ready yet).

**Comment by xxxxj-up** [comment]
> @xxxxj-up well, you are right, but it was not expected that anyone would try to use it directly. It is intended to be installed and updated with an installer application (which is not ready yet).

@insolor Since I will be reading the code, I will do a pre-reading attempt
